#!/bin/bash

if [ $# -ne 1 ] && [ $# -ne 3 ]
then
  echo "wrong number of command line arguments"
  echo "Usage: script2 -?"
  echo "    or"
  echo "       script2 <file_to_be_deleted>"
  echo "    or"
  echo "       script2 <number_of_lines> <text> <outfile>"
  exit
fi

if [ $# -eq 1 ]
then
  if [ "$1" == "-?" ]
  then
    echo "Usage: script2 -?"
    echo "    or"
    echo "       script2 <file_to_be_deleted>"
    echo "    or"
    echo "       script2 <number_of_lines> <text> <outfile>"
    exit
  else
    echo "going to remove file $1 (y/n)"
    read input
    if [ "${input:0:1}" == "y" ]
    then
      echo "removing file $1"
      rm $1
    else
      echo "not removing file $1"
      exit
    fi
  fi
  exit
fi

if [ $# -eq 3 ]
then
    for (( COUNTER = 1;COUNTER <= $1;COUNTER += 1 ))
        do
            echo "Line$COUNTER:$2+$COUNTER" >> $3
        done
    cat $3
    exit
fi